### ISSUE TITLE
[Frontend] UI fix mouse events in-sensitive issue

### ISSUE THREAD

**Issue by Ohyeon5** [Ohyeon5/syn-search#7]
# Goal
UI components were extremely insensitive to mouse-related events. It could be because of delayed resource loading, etc. Need to fix it to have normal behavior. At the moment, we could input entities by randomly changing the window size

# Task list
- [ ] Capture the reason for the problem
- [ ] Resolve the issue
- [ ] Document the reason in wiki
- [ ] Push to the `web-app` branch (for the CD)
