### ISSUE TITLE
[Backend] Set up github action for web app deployment

### ISSUE THREAD

**Issue by Ohyeon5** [Ohyeon5/syn-search#8]
# Goal 
Set up GitHub action for the web app deployment. 

> Ref: https://learn.microsoft.com/en-us/training/modules/deploy-run-container-app-service/

# Task list
- [x] Create Docker image
- [x] Set up github action to deploy it
- [x] Connect it with UI (static web app)
